### PR TITLE
Fixes for typo and directory changes in DYAD

### PR DESCRIPTION
**Pull request by hariharan-devarajan**
So, the new structure didn't copy the images in the right place. Additionally, the path changes were not propagated into the notebook.

I fixed all typos. But the image need a fresh install of dlio_benchmark as it seems the architecture is not aching. I am getting `illegal instructions` error.

@ilumsden Can u help me fix the image so that I can continue testing. Some things till left to do are 

Module 4: 04_flux_tutorial_conclusions.ipynb the file is not found.
Then to run the code,
1. The directory path is wrong. (Fixed)
2. seems like the architecture has changed. I get illegal instructions on the existing DLIO Benchmark code
3. When i run the shutting down of service i get flux-exec: flux_reactor_run: Invalid argument

### CODE REVIEW

**Comment by vsoch** [comment]
@hariharan-devarajan it looks like the build was OK, at least in the CI! Apologies for the path changes without updating the notebook, I didn't even open it, because I wouldn't have been oriented to work on it. I'll leave you and @ilumsden to work on this, but please ping me if/when it's ready for review.

**Comment by vsoch** [comment]
A few nits preparing for future review:

- Commit meaningfully (I am working on this too) with the format `category: message` and then the longer statement below it that describes the change.
- Make sure there is not an empty cell added to the end

**Comment by ilumsden** [comment]
@hariharan-devarajan regarding the `illegal instructions` stuff, what architecture is the computer on which you built the container? Also, what command produced this error? If you could share a screenshot of the error, that would help too.

In my experience, errors like this usually occur on ARM systems (e.g., newer Macs) due to an architecture mismatch between the host system and the container. If this is the issue, it's easily solved using the `--platform` flag.

**Comment by hariharan-devarajan** [comment]
> @hariharan-devarajan regarding the `illegal instructions` stuff, what architecture is the computer on which you built the container? Also, what command produced this error? If you could share a screenshot of the error, that would help too.
> 
> In my experience, errors like this usually occur on ARM systems (e.g., newer Macs) due to an architecture mismatch between the host system and the container. If this is the issue, it's easily solved using the `--platform` flag.

Currently, I am stuck with some deadlines. I would appreciate if u could test the Tutorial. If you have any issues, I can probably help u out. Let me know if u can try this out or not.

**Comment by ilumsden** [comment]
Sounds good. That's my top priority this week (unless I need to do more work on a paper, but I suspect my main work for that paper is done).

**Comment by ilumsden** [comment]
@vsoch the DYAD notebook is now fully working. I tested it on an x86 instance from Jetstream cloud.

I still have to rebase this PR, but, other than that, this is ready for your review.

**Comment by ilumsden** [comment]
@hariharan-devarajan since the `2024-radiuss-aws` branch from this repo has already been merged, you will need to edit the PR to merge into `master`.

**Comment by hariharan-devarajan** [comment]
What do u mean edit? U mean base it off master?


The changes I did were minor. Could we just apply the changes on a new PR?

**Comment by ilumsden** [comment]
We could do that if you'd prefer. The stuff I've added to get everything working is pretty minor too.

**Comment by vsoch** [comment]
Please rebase before review - thank you!

**Comment by ilumsden** [comment]
@vsoch @hariharan-devarajan so that we can merge into `master`, I opened #43. That PR is the same as this one plus rebasing.

@vsoch please review that PR.

**Pull request closed without merging**
