### PR TITLE
ECP-2020: Add & adapt workflow examples for ECP 2020 Tutorial

### PR DESCRIPTION
**Pull request by SteVwonder**

### CODE REVIEW

**Comment by SteVwonder** [comment]
Note: one other manual change that I couldn't figure out how to add, but to get example10 to print the same way under both `sched-simple` and `qmanager`, I had to add `FLUX_QMANAGER_OPTIONS="queue-policy=easy"` to the qmanager rc1.d script.

**Comment by SteVwonder** [comment]
@dongahn: any objection to merging this before the tutorial? Would be good if users could see the readmes in their browsers on the main fork and master branch.

**Comment by dongahn** [comment]
@SteVwonder: LGTM. Merging.

**Comment by SteVwonder** [comment]
Thanks @dongahn!

**Pull request merged**
